print("hlw this is me ")
name = input()
print('nice to me u i am ' +name)
print('how old are you ?')
age = input()
birthyear = 2023-int(age)
print(birthyear)
answer = str(birthyear)
print ('You are born in '+answer)