mystr = "I am Moyeen"
print(mystr[5])
print(len(mystr[0:]))
print(mystr[2:5])
print(mystr[0:78])
print(mystr[0:5:2])
print(mystr[::2])
print(mystr[-4:-2])
print(mystr[8:-2])
print(mystr[::-1])
print(mystr[::-2])
print(mystr.isalnum())
print(mystr.isalnum())
print(mystr.endswith("een"))
print(mystr.count("e"))
print(mystr.capitalize())
print(mystr.find("am"))
print(mystr.upper())

